#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import json
import os

url = 'http://music.sonimei.cn/'
body = {"input": "薛之谦", "filter": "name", "type": "qq","page":"3"}
headers = {
"X-Requested-With": "XMLHttpRequest"
}
#print type(body)
#print type(json.dumps(body))
# 这里有个细节，如果body需要json形式的话，需要做处理
# 可以是data = json.dumps(body)
response = requests.post(url, data = body, headers = headers)
# 也可以直接将data字段换成json字段，2.4.3版本之后支持
# response  = requests.post(url, json = body, headers = headers)

# 返回信息
dic = json.loads(response.text)
def mkdir(path):
    path = path.strip()
    path = path.rstrip("\\")
    isExists = os.path.exists(path)

    if not isExists:
        os.makedirs(path)
        return True
    else:
        return False
for info in dic["data"]:
    print ("作者："+info["author"],"歌曲名称："+info["title"],"图像地址："+info["pic"],"音乐地址："+info["url"])

    video=requests.get(info["url"])

    mkdir('/Users/leishangming/Desktop/music/'+ '%s' % info["author"])

    with open('/Users/leishangming/Desktop/music/'+ '%s' % info["author"]+ '/%s.mp3' % info["title"],'wb') as f:
         f.write(video.content)